- 'lib/**/*.js'
- 'compiled/Collection/Collection.js'
- 'compiled/Collection/BaseCollector.js'
- 'compiled/Collection/**/*.js'
- 'compiled/Actor/BaseActor.js'
- 'compiled/Actor/**/*.js'
- 'compiled/Graphic/BaseGraphic.js'
- 'compiled/Graphic/**/*.js'
- 'compiled/Scene/BaseScene.js'
- 'compiled/Scene/**/*.js'
- 'compiled/*.js'
